name: Test Github Actions Dynamic Matrix
on:
  workflow_dispatch:
  
jobs:
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          git clone --branch build-all https://github.com/BinauralAudio/dsoal.git .
      - run: |
          git log --format="%h %d" |grep -v '(tag:' | awk '{print $1}'
