name: Test
on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --branch build-all https://github.com/BinauralAudio/dsoal.git .
      - run: |
          git log --format="%h %d" |grep -v '(tag:' | awk '{print $1}'
