name: Untagged build

on:
  push:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          git clone --branch build-all https://github.com/BinauralAudio/dsoal.git .
          echo "value=[$(git rev-list HEAD)]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
      
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{needs.setup.outputs.matrix}} | tr '\n' ', '
    steps:
      - run: |
          echo "${{ matrix.value }}"
