name: Untagged build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - '.github/workflows/Tagged.yaml'
#  schedule:
#  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  Configuration: Release
  DSOALRepo: ${{github.repository}}
  DSOALBranch: ${{github.ref_name}}
  OpenALSoftRepo: kcat/openal-soft
  OpenALSoftBranch: master
  GH_TOKEN: ${{github.token}}

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          git clone --branch build-all https://github.com/BinauralAudio/dsoal.git .
          echo "DSOALCommitHash=[\"$(git rev-list HEAD --max-count=2 | sed ':a;N;$!ba;s/\n/\", \"/g')\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.DSOALCommitHash }}"
    outputs:
      matrix: ${{ steps.matrix.outputs.DSOALCommitHash }}

  Build:
    needs: [ setup ]
    name: ${{matrix.config.name}}
    runs-on: windows-2019
    strategy:
      max-parallel: 1
      matrix:
        DSOALCommitHash: ${{fromJSON(needs.setup.outputs.matrix)}}
        config:
        - {
            name: "Win32",
            platform: "Win32"
          }
        - {
            name: "Win64",
            platform: "x64"
          }
    steps:
    
    - name: Clone DSOAL
      run: |
        git clone --branch ${{env.DSOALBranch}} https://github.com/${{env.DSOALRepo}}.git .
        git reset --hard ${{matrix.DSOALCommitHash}}
        echo "DSOALCommitHashShort=$(git rev-parse --short=8 HEAD)" >> $env:GITHUB_ENV
        echo "DSOALCommitDate=$(git show -s --date=iso-local --format=%cd)" >> $env:GITHUB_ENV
        echo "DSOALCommitDateShort=$(git show -s --date=iso-local --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV
        echo "DSOALCommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        
    - name: Clone OpenAL Soft
      run: |
        git clone --branch ${{env.OpenALSoftBranch}} https://github.com/${{env.OpenALSoftRepo}}.git
        cd "openal-soft"
        git reset --hard $(git rev-list --before=${{env.DSOALCommitDateShort}} HEAD --max-count=1)
        echo "OpenALSoftCommitHashShort=$(git rev-parse --short=8 HEAD)" >> $env:GITHUB_ENV
        echo "OpenALSoftCommitDate=$(git show -s --date=iso-local --format=%cd)" >> $env:GITHUB_ENV
        echo "OpenALSoftCommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV

    - name: Build
      run: |
        cmake -B "${{github.workspace}}/openal-soft/build" -DCMAKE_Configuration=${{env.Configuration}} -A ${{matrix.config.platform}} -DALSOFT_BUILD_ROUTER=ON -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=ON -DALSOFT_REQUIRE_WASAPI=ON "${{github.workspace}}/openal-soft"
        cmake --build "${{github.workspace}}/openal-soft/build" --config ${{env.Configuration}}
        cd "${{github.workspace}}"
        cmake -B "${{github.workspace}}/build" -A ${{matrix.config.platform}} -DOPENAL_INCLUDE_DIR=openal-soft/include/AL -DOPENAL_LIBRARY=openal-soft/build/Release/OpenAL32.lib
        cmake --build "${{github.workspace}}/build" --config ${{env.Configuration}}

    - name: Collect
      run: |
        mkdir -p "build/Release/DSOAL/${{matrix.config.name}}/Documentation"
        move "${{github.workspace}}/build/${{env.Configuration}}/dsound.dll"                                   "build/Release/DSOAL/${{matrix.config.name}}/dsound.dll"
        move "${{github.workspace}}/openal-soft/build/${{env.Configuration}}/soft_oal.dll"                     "build/Release/DSOAL/${{matrix.config.name}}/dsoal-aldrv.dll"
        copy "${{github.workspace}}/openal-soft/alsoftrc.sample"                                               "build/Release/DSOAL/${{matrix.config.name}}/alsoft.ini"
        copy "${{github.workspace}}/README.md"                                                                 "build/Release/DSOAL/${{matrix.config.name}}/Documentation/DSOAL-ReadMe.txt"
        copy "${{github.workspace}}/LICENSE"                                                                   "build/Release/DSOAL/${{matrix.config.name}}/Documentation/DSOAL-License.txt"
        echo "${{env.DSOALRepo}}" >>                                                                           "build/Release/DSOAL/${{matrix.config.name}}/Documentation/DSOAL-Version.txt"
        echo "r${{env.DSOALCommitCount}}@${{env.DSOALCommitHashShort}} ${{env.DSOALBranch}}" >>                "build/Release/DSOAL/${{matrix.config.name}}/Documentation/DSOAL-Version.txt"
        echo "${{env.DSOALCommitDate}}" >>                                                                     "build/Release/DSOAL/${{matrix.config.name}}/Documentation/DSOAL-Version.txt"
        copy "${{github.workspace}}/openal-soft/README.md"                                                     "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-ReadMe.txt"
        copy "${{github.workspace}}/openal-soft/COPYING"                                                       "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-License.txt"
        copy "${{github.workspace}}/openal-soft/BSD-3Clause"                                                   "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-BSD-3Clause.txt"
        copy "${{github.workspace}}/openal-soft/ChangeLog"                                                     "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-ChangeLog.txt"
        echo "${{env.OpenALSoftRepo}}" >>                                                                      "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-Version.txt"
        echo "r${{env.OpenALSoftCommitCount}}@${{env.OpenALSoftCommitHashShort}} ${{env.OpenALSoftBranch}}" >> "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-Version.txt"
        echo "${{env.OpenALSoftCommitDate}}" >>                                                                "build/Release/DSOAL/${{matrix.config.name}}/Documentation/OpenALSoft-Version.txt"
        cp -R "build/Release/DSOAL" "build/Release/DSOAL+HRTF"
        mv "build/Release/DSOAL/${{matrix.config.name}}/alsoft.ini" "build/Release/DSOAL/${{matrix.config.name}}/Documentation/alsoft.ini"
        curl https://raw.githubusercontent.com/${{needs.Build.outputs.OpenALSoftRepo}}/${{needs.Build.outputs.OpenALSoftBranch}}/configs/HRTF/alsoft.ini -o "build/Release/DSOAL+HRTF/${{matrix.config.name}}/alsoft.ini"
        
    - name: Compress
      run: |
        cd build/Release
        7z a DSOAL.zip      ./DSOAL/*
        7z a DSOAL+HRTF.zip ./DSOAL+HRTF/*

    - name: Release
      run: |
        gh release create r${{env.DSOALCommitCount}} --title "DSOAL r${{env.DSOALCommitCount}}@${{env.DSOALCommitHashShort}}" --target ${{env.DSOALBranch}} --generate-notes --latest=false --prerelease
        gh release upload r${{env.DSOALCommitCount}} build/Release/DSOAL.zip build/Release/DSOAL+HRTF.zip
