name: Untagged build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - '.github/workflows/Tagged.yaml'
#  schedule:
#  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  Configuration: Release
  DSOALRepo: ${{github.repository}}
  DSOALBranch: ${{github.ref_name}}
  OpenALSoftRepo: kcat/openal-soft
  OpenALSoftBranch: master

jobs:


  setup:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          git clone --branch build-all https://github.com/BinauralAudio/dsoal.git .
          git reset --hard 98584ab11d231d36488bc055bdeb19b607706bc6
          echo "DSOALCommitHash=[\"$(git rev-list HEAD | sed ':a;N;$!ba;s/\n/\", \"/g')\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.DSOALCommitHash }}"
    outputs:
      matrix: ${{ steps.matrix.outputs.DSOALCommitHash }}

  Build:
    needs: [ setup ]
    name: ${{matrix.config.name}}
    runs-on: linux-latest
    strategy:
      matrix:
        DSOALCommitHash: ${{fromJSON(needs.setup.outputs.matrix)}}
        config:
        - {
            name: "Win32",
            platform: "Win32"
          }
        - {
            name: "Win64",
            platform: "x64"
          }
    steps:
    
    - name: Clone DSOAL
      run: |
        git clone --branch ${{env.DSOALBranch}} https://github.com/${{env.DSOALRepo}}.git .
        git reset --hard ${{matrix.DSOALCommitHash}}
        git clone --branch ${{env.OpenALSoftBranch}} https://github.com/${{env.OpenALSoftRepo}}.git
        echo "DSOALCommitHashShort=$(git rev-parse --short=8 HEAD)" >> $env:GITHUB_ENV
        echo "DSOALCommitDate=$(git show -s --date=iso-local --format=%cd)" >> $env:GITHUB_ENV
        echo "DSOALCommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        cd "openal-soft"
        echo "OpenALSoftCommitHashShort=$(git rev-parse --short=8 HEAD)" >> $env:GITHUB_ENV
        echo "OpenALSoftCommitDate=$(git show -s --date=iso-local --format=%cd)" >> $env:GITHUB_ENV
        echo "OpenALSoftCommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        cmake -B "${{github.workspace}}/openal-soft/build" -DCMAKE_Configuration=${{env.Configuration}} -A ${{matrix.config.platform}} -DALSOFT_BUILD_ROUTER=ON -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=ON -DALSOFT_REQUIRE_WASAPI=ON "${{github.workspace}}/openal-soft"
        cmake --build "${{github.workspace}}/openal-soft/build" --config ${{env.Configuration}}
        ls -R
        cmake -B "${{github.workspace}}/build" -A ${{matrix.config.platform}} -DOPENAL_INCLUDE_DIR=openal-soft/include -DOPENAL_LIBRARY=openal-soft/include
        cmake --build "${{github.workspace}}/build" --config ${{env.Configuration}}
        ls -R
        mkdir "DSOAL"
        mkdir "DSOAL/Documentation"
        move "${{github.workspace}}/build/${{env.Configuration}}/dsound.dll"                                   "DSOAL/dsound.dll"
        copy "${{github.workspace}}/README.md"                                                                 "DSOAL/Documentation/DSOAL-ReadMe.txt"
        copy "${{github.workspace}}/LICENSE"                                                                   "DSOAL/Documentation/DSOAL-License.txt"
        echo "${{env.DSOALRepo}}" >>                                                                           "DSOAL/Documentation/DSOAL-Version.txt"
        echo "r${{env.DSOALCommitCount}}@${{env.DSOALCommitHashShort}} ${{env.DSOALBranch}}" >>                "DSOAL/Documentation/DSOAL-Version.txt"
        echo "${{env.DSOALCommitDate}}" >>                                                                     "DSOAL/Documentation/DSOAL-Version.txt"
        7z a DSOAL_r${{env.DSOALCommitCount}}@${{env.DSOALCommitHashShort}}-${{matrix.config.name}}.zip       ./DSOAL/*
        gh release create r${{env.DSOALCommitCount}} --title "DSOAL r${{env.DSOALCommitCount}}@${{env.DSOALCommitHashShort}}" --target ${{env.DSOALBranch}} --generate-notes --latest=false --prerelease
        gh release upload r${{env.DSOALCommitCount}} DSOAL_r${{env.DSOALCommitCount}}@${{env.DSOALCommitHashShort}}-${{matrix.config.name}}.zip
